# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprarArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('receta', models.CharField(blank=True, max_length=5000, null=True)),
                ('tipo_de_comida', models.CharField(blank=True, choices=[('CER', 'Cereal'), ('FRU', 'Fruta'), ('VER', 'Verdura'), ('CAP', 'Capricho')], max_length=20, null=True)),
            ],
        ),
    ]
